channels:
  # Define conda channels here. 
  - conda-forge

dependencies:
  # Define conda packages here. 
  # If available, always prefer the conda version of a package, installation will be faster and more efficient.
  # https://anaconda.org/search  
  - python=3.11.0
  - nodejs=16.14.2

  - pip=22.3.1
  - pip:
    # Define pip packages here. 
    # https://pypi.org/
    - rpaframework==20.0.2 # https://rpaframework.org/releasenotes.html
    - robotframework-browser==14.4.1
    - pystray==0.19.4
    - psutil==5.9.4
    - keyring==23.13.1

rccPostInstall:
  - rfbrowser init
