# Playwright specific dependencies
# - replace conda.yaml from main directory with this content, if Playwright is used instead of Selenium

channels:
  # Define conda channels here. 
  - conda-forge

dependencies:
  # Define conda packages here. 
  # If available, always prefer the conda version of a package, installation will be faster and more efficient.
  # https://anaconda.org/search  
  - python=3.11.5
  - nodejs=18.17.1

  - pip=23.1.2
  - pip:
    # Define pip packages here. 
    # https://pypi.org/
    - rpaframework==26.1.0 # https://rpaframework.org/releasenotes.html
    - robotframework-browser==17.4.0
    - pystray==0.19.4
    - psutil==5.9.5
    - keyring==24.2.0

rccPostInstall:
  - rfbrowser init
